# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjectCoffee' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjectCoffee

pod "Alamofire"
pod "SDWebImage"
pod "SnapKit"

  target 'ProjectCoffeeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProjectCoffeeUITests' do
    # Pods for testing
  end

end
